# Generated by Django 6.0.6 on 2026-07-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtube_url',
            new_name='video_url',
        ),
    ]
