# Generated by Django 6.0.6 on 2026-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_youtube_url_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for the video', null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(help_text='URL of the yoga video'),
        ),
        migrations.AlterField(
            model_name='videobenefit',
            name='benefit',
            field=models.TextField(help_text='Benefit of performing this yoga video'),
        ),
        migrations.AlterField(
            model_name='videostep',
            name='step',
            field=models.TextField(help_text='Step to perform this yoga video'),
        ),
    ]
