# Generated by Django 6.0.6 on 2026-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_thumbnail_alter_video_video_url_and_more'),
        ('yogig_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionvideo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sessionvideo',
            constraint=models.UniqueConstraint(fields=('session', 'video'), name='unique_session_video'),
        ),
    ]
